# Secrets are managed using a .env file in the root folder. Don't put sensitive data in this file!

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
