# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71ae8a03fc5475341e00bc040e7786f6732c1c5146c28006e7d821cca55ea90248a537d6b7da4c464534975399c3fdb8193316f5502a91345466e85ca83a96e9

test:
  secret_key_base: b3bf8ef7acff6aab3e5dbac607c038769d0c2f10c578a386912e34f1551fdb657ef8b4c65324819fd5d5146f0e5ed0e0442126157ae0fae3a3f54ff809dd6b49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
